// Environment Setup Page JavaScript
document.addEventListener('DOMContentLoaded', () => {
    // Only run on environment page
    const environmentForm = document.getElementById('environment-form');
    if (!environmentForm) return;

    // Setup checkbox toggle handlers
    setupCheckboxToggle('install_java', 'java-options');
    setupCheckboxToggle('install_tomcat', 'tomcat-options');
    setupCheckboxToggle('install_database', 'database-options');
    setupCheckboxToggle('install_agent_prereqs', 'agent-prereqs-info');

    // No version selector needed since we only support Tomcat 10

    // Setup form submission
    environmentForm.addEventListener('submit', (event) => {
        event.preventDefault();
        generateEnvironmentScript();
    });

    // Setup copy button
    const copyButton = document.getElementById('copy-button');
    if (copyButton) {
        copyButton.addEventListener('click', () => {
            const commandText = document.getElementById('generated-command').innerText;
            navigator.clipboard.writeText(commandText).then(() => {
                alert('Copied!');
            }, (err) => {
                console.error('Failed to copy command: ', err);
                alert('Copy failed.');
            });
        });
    }
});

function setupCheckboxToggle(checkboxId, sectionId) {
    const checkbox = document.getElementById(checkboxId);
    const section = document.getElementById(sectionId);
    if (checkbox && section) {
        checkbox.addEventListener('change', () => {
            section.style.display = checkbox.checked ? 'block' : 'none';
        });
    }
}

function generateEnvironmentScript() {
    const osEnvironment = document.getElementById('os_environment').value;
    const installJava = document.getElementById('install_java').checked;
    const installTomcat = document.getElementById('install_tomcat').checked;
    const installDatabase = document.getElementById('install_database').checked;
    const installAgentPrereqs = document.getElementById('install_agent_prereqs').checked;

    let commands = [];
    let downloadLinks = [];
    let showManualDownloads = false;

    // Windows - show only download links
    if (osEnvironment === 'windows') {
        if (installJava) {
            downloadLinks.push({
                title: 'Download Oracle JRE for Windows',
                url: 'http://www.oracle.com/technetwork/java/javase/downloads/index.html',
                description: 'Oracle Java Runtime Environment'
            });
            downloadLinks.push({
                title: 'Download OpenJDK for Windows',
                url: 'https://developers.redhat.com/products/openjdk/download/',
                description: 'Red Hat OpenJDK (Free and Open Source)'
            });
        }

        if (installTomcat) {
            downloadLinks.push({
                title: 'Download Apache Tomcat 10 for Windows',
                url: 'https://tomcat.apache.org/download-10.cgi',
                description: 'Apache Tomcat 10 Windows Service Installer or ZIP archive'
            });
        }

        if (installDatabase) {
            downloadLinks.push({
                title: 'Stonebranch Database Installation Guide',
                url: 'https://stonebranchdocs.atlassian.net/wiki/spaces/UC79/pages/1614463314/Installing+a+Database',
                description: 'Complete database installation instructions for all supported databases'
            });
        }

        showManualDownloads = true;
        commands.push('# Windows Installation');
        commands.push('# Please download and install the required components using the links provided below.');
        commands.push('# Follow the installation wizards for each component.');
    } else {
        // Linux - generate bash script
        // Add shebang and header
        commands.push('#!/bin/bash');
        commands.push('# Universal Controller Environment Setup Script');
        commands.push('# Generated by Installation Command Generator');
        commands.push('');

        // Agent Prerequisites
        if (installAgentPrereqs) {
            const agentPrereqsCommand = generateAgentPrereqsCommand(osEnvironment);
            if (agentPrereqsCommand) {
                commands.push('# Install Agent Prerequisites');
                commands.push(agentPrereqsCommand);
                commands.push('');
            }
        }

        // Java Installation
        if (installJava) {
            const javaVersion = document.getElementById('java_version').value;
            const javaCommand = generateJavaCommand(osEnvironment, javaVersion);
            if (javaCommand) {
                commands.push('# Install Java ' + javaVersion);
                commands.push(javaCommand);
                commands.push('');
            }
        }

        // Tomcat Installation
        if (installTomcat) {
            const tomcatMethod = document.getElementById('tomcat_method').value;

            if (tomcatMethod === 'package') {
                const tomcatCommands = generateTomcatPackageCommand(osEnvironment);
                if (tomcatCommands.length > 0) {
                    commands.push('# Install Tomcat 10 via Package Manager');
                    commands.push(...tomcatCommands);
                    commands.push('');
                }
            } else {
                // Manual installation
                const tomcatCommands = generateTomcatManualCommand();
                commands.push('# Install Tomcat 10 Manually');
                commands.push(...tomcatCommands);
                commands.push('');

                // Add download link
                downloadLinks.push({
                    title: 'Download Tomcat 10 Manually',
                    url: getTomcatDownloadUrl(),
                    description: 'Apache Tomcat 10 tar.gz archive'
                });
                showManualDownloads = true;
            }
        }

        // Database Installation
        if (installDatabase) {
            const databaseType = document.getElementById('database_type').value;
            const dbCommands = generateDatabaseCommand(osEnvironment, databaseType);
            if (dbCommands.length > 0) {
                commands.push('# Install ' + capitalizeFirst(databaseType));
                commands.push(...dbCommands);
                commands.push('');
            }

            // Always add database documentation link
            downloadLinks.push({
                title: 'Stonebranch Database Installation Guide',
                url: 'https://stonebranchdocs.atlassian.net/wiki/spaces/UC79/pages/1614463314/Installing+a+Database',
                description: 'Detailed database setup and configuration instructions'
            });
            showManualDownloads = true;
        }

        // Add verification section
        if (installJava || installTomcat || installDatabase) {
            commands.push('# Verify Installations');
            if (installJava) {
                commands.push('java -version');
            }
            if (installTomcat && document.getElementById('tomcat_method').value === 'package') {
                if (osEnvironment === 'ubuntu') {
                    commands.push('systemctl status tomcat10');
                } else {
                    commands.push('systemctl status tomcat');
                }
            }
            if (installDatabase) {
                const dbType = document.getElementById('database_type').value;
                if (dbType === 'postgres') {
                    commands.push('psql --version');
                } else {
                    commands.push('mysql --version');
                }
            }
        }
    }

    // Display generated commands
    const commandOutput = document.getElementById('command-output');
    const generatedCommand = document.getElementById('generated-command');
    generatedCommand.textContent = commands.join('\n');
    commandOutput.style.display = 'block';

    // Display manual download links if needed
    const manualDownloadSection = document.getElementById('manual-download-section');
    const downloadLinksDiv = document.getElementById('download-links');

    if (showManualDownloads && downloadLinks.length > 0) {
        downloadLinksDiv.innerHTML = downloadLinks.map(link =>
            `<p><a href="${link.url}" target="_blank" class="download-link">${link.title}</a>${link.description ? '<br><span style="font-size: 12px; color: #666;">' + link.description + '</span>' : ''}</p>`
        ).join('');
        manualDownloadSection.style.display = 'block';
    } else {
        manualDownloadSection.style.display = 'none';
    }

    // Scroll to output
    setTimeout(() => {
        commandOutput.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
}

function generateJavaCommand(osEnvironment, javaVersion) {
    switch (osEnvironment) {
        case 'aws':
            return `sudo yum install java-${javaVersion}-amazon-corretto-headless -y`;
        case 'rhel':
            return `sudo yum install java-${javaVersion}-openjdk-headless -y`;
        case 'ubuntu':
            return `sudo apt-get update && sudo apt-get install openjdk-${javaVersion}-jdk-headless -y`;
    }
    return '';
}

function generateTomcatPackageCommand(osEnvironment) {
    const commands = [];

    switch (osEnvironment) {
        case 'aws':
        case 'rhel':
            commands.push('sudo yum install tomcat10 -y');
            break;
        case 'ubuntu':
            commands.push('sudo apt-get update && sudo apt-get install tomcat10 -y');
            break;
        default:
            return [];
    }

    // Add service management commands
    commands.push('sudo systemctl enable tomcat10');
    commands.push('sudo systemctl start tomcat10');
    commands.push('sudo systemctl status tomcat10');
    commands.push('curl localhost:8080');

    return commands;
}

function generateTomcatManualCommand() {
    const commands = [];
    const downloadUrl = getTomcatDownloadUrl();
    const filename = downloadUrl.split('/').pop();
    const dirname = filename.replace('.tar.gz', '');

    commands.push('# Download Tomcat 10');
    commands.push(`wget ${downloadUrl}`);
    commands.push('');
    commands.push('# Extract Tomcat');
    commands.push(`tar -xvzf ${filename}`);
    commands.push('');
    commands.push('# Move to /opt and create symlink');
    commands.push(`sudo mv ${dirname} /opt/`);
    commands.push(`sudo ln -s /opt/${dirname} /opt/tomcat`);
    commands.push('');
    commands.push('# Set permissions');
    commands.push('sudo chown -R $USER:$USER /opt/tomcat');
    commands.push('sudo chmod +x /opt/tomcat/bin/*.sh');

    return commands;
}

function getTomcatDownloadUrl() {
    return 'https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz';
}

function generateAgentPrereqsCommand(osEnvironment) {
    switch (osEnvironment) {
        case 'aws':
            return 'sudo yum install libxcrypt-compat -y';
        case 'rhel':
            return 'sudo yum install libxcrypt-compat -y';
        case 'ubuntu':
            // Ubuntu typically doesn't need this package
            return '';
    }
    return '';
}

function generateDatabaseCommand(osEnvironment, databaseType) {
    const commands = [];

    switch (osEnvironment) {
        case 'aws':
        case 'rhel':
            if (databaseType === 'mysql') {
                commands.push('sudo yum install mysql-server -y');
                commands.push('sudo systemctl start mysqld');
                commands.push('sudo systemctl enable mysqld');
            } else if (databaseType === 'mariadb') {
                commands.push('sudo yum install mariadb105-server -y');
                commands.push('sudo systemctl start mariadb');
                commands.push('sudo systemctl enable mariadb');
            } else if (databaseType === 'postgres') {
                commands.push('sudo yum install postgresql-server postgresql-contrib -y');
                commands.push('sudo postgresql-setup --initdb');
                commands.push('sudo systemctl start postgresql');
                commands.push('sudo systemctl enable postgresql');
            }
            break;
        case 'ubuntu':
            if (databaseType === 'mysql') {
                commands.push('sudo apt-get update && sudo apt-get install mysql-server -y');
                commands.push('sudo systemctl start mysql');
                commands.push('sudo systemctl enable mysql');
            } else if (databaseType === 'mariadb') {
                commands.push('sudo apt-get update && sudo apt-get install mariadb-server -y');
                commands.push('sudo systemctl start mariadb');
                commands.push('sudo systemctl enable mariadb');
            } else if (databaseType === 'postgres') {
                commands.push('sudo apt-get update && sudo apt-get install postgresql postgresql-contrib -y');
                commands.push('sudo systemctl start postgresql');
                commands.push('sudo systemctl enable postgresql');
            }
            break;
    }

    return commands;
}

function capitalizeFirst(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

// Helper function for copying code (can be called from HTML)
function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
        alert('Copied to clipboard!');
    }, (err) => {
        console.error('Failed to copy: ', err);
        alert('Copy failed.');
    });
}
